CREATE TABLE "DB2INST1"."TEST_CASES"  (
		  "TEST_ID" INTEGER NOT NULL ,
		  "TEST_DATA" VARCHAR(1000 OCTETS) NOT NULL ,
		  "SERVICE_NAME" VARCHAR(100 OCTETS) NOT NULL ,
		  "TEST_WRITE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 0 )
		 IN "USERSPACE1"
		 ORGANIZE BY ROW  ;
ALTER TABLE "DB2INST1"."TEST_CASES"
	ADD PRIMARY KEY
		("TEST_ID")
	ENFORCED ;
-- Contains the endpoint of the services to be tested
CREATE TABLE "DB2INST1"."SERVICE_DESCRIPTION"  (
		  "SERVICE_NAME" VARCHAR(255 OCTETS) NOT NULL ,
		  "ENDPOINT_NEW" VARCHAR(255 OCTETS) ,
		  "ENDPOINT_OLD" VARCHAR(255 OCTETS) )
		 IN "USERSPACE1"
		 ORGANIZE BY ROW  ;
ALTER TABLE "DB2INST1"."SERVICE_DESCRIPTION"
	ADD PRIMARY KEY
		("SERVICE_NAME")
	ENFORCED ;

